pin auto_schema to specific versions
add python-dateutil dependency

release auto_schema version 0.0.10

was seeing this error:

```
Traceback (most recent call last):
  File "/opt/venv/bin/auto_schema", line 8, in <module>
    sys.exit(main())
  File "/opt/venv/lib/python3.8/site-packages/auto_schema/cli/__init__.py", line 72, in main
    r.run()
  File "/opt/venv/lib/python3.8/site-packages/auto_schema/runner.py", line 187, in run
    self._apply_changes(diff)
  File "/opt/venv/lib/python3.8/site-packages/auto_schema/runner.py", line 202, in _apply_changes
    raise err
  File "/opt/venv/lib/python3.8/site-packages/auto_schema/runner.py", line 196, in _apply_changes
    self.revision(diff)
  File "/opt/venv/lib/python3.8/site-packages/auto_schema/runner.py", line 225, in revision
    self.cmd.revision(message)
  File "/opt/venv/lib/python3.8/site-packages/auto_schema/command.py", line 50, in revision
    command.revision(self.alembic_cfg, message, autogenerate=True)
  File "/opt/venv/lib/python3.8/site-packages/alembic/command.py", line 234, in revision
    scripts = [script for script in revision_context.generate_scripts()]
  File "/opt/venv/lib/python3.8/site-packages/alembic/command.py", line 234, in <listcomp>
    scripts = [script for script in revision_context.generate_scripts()]
  File "/opt/venv/lib/python3.8/site-packages/alembic/autogenerate/api.py", line 600, in generate_scripts
    yield self._to_script(generated_revision)
  File "/opt/venv/lib/python3.8/site-packages/alembic/autogenerate/api.py", line 505, in _to_script
    return self.script_directory.generate_revision(
  File "/opt/venv/lib/python3.8/site-packages/alembic/script/base.py", line 664, in generate_revision
    create_date = self._generate_create_date()
  File "/opt/venv/lib/python3.8/site-packages/alembic/script/base.py", line 592, in _generate_create_date
    raise util.CommandError(
alembic.util.exc.CommandError: The library 'python-dateutil' is required for timezone support
Error: exit status 1
```